name: Deploy to Server

on:
  push:
    branches: [ dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      run: docker build -t hello-world-backend .
    
    - name: Save Docker image
      run: docker save hello-world-backend | gzip > hello-world-backend.tar.gz
    
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        source: "hello-world-backend.tar.gz,docker-compose.yml"
        target: "/home/${{ secrets.SERVER_USER }}/app"
    
    - name: Deploy on server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASS }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/app
          docker load < hello-world-backend.tar.gz
          docker-compose down
          docker-compose up -d
          docker system prune -f